services:
    cassandra:
      build:
        context: .
        dockerfile: Dockerfile.cassandra
      container_name: cassandra
      command: >
        bash -c "
        export JVM_OPTS='-javaagent:/opt/debezium-cassandra/cassandra-agent.jar=/opt/debezium-cassandra/conf/debezium-connector.properties';
        docker-entrypoint.sh cassandra -f
        "
      ports:
        - "9042:9042"
      volumes:
        - cassandra_data:/var/lib/cassandra
        - ./../config/cassandra.yaml:/etc/cassandra/cassandra.yaml

volumes:
  cassandra_data: