# cassandra node info
cassandra.hosts=localhost
cassandra.port=9042

# commit log info
cassandra.commitlog.dir=/var/lib/cassandra/commitlog

# kafka info
kafka.bootstrap.servers=kafka:9092
kafka.topic=cassandra.cdc

# data converters
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
