FROM cassandra:5.0.6

# dowload debezium connector
RUN curl -L https://repo1.maven.org/maven2/io/debezium/debezium-connector-cassandra-5/3.3.2.Final/debezium-connector-cassandra-5-3.3.2.Final-plugin.tar.gz \
    | tar xz -C /opt

#  copy debezium agent property file
COPY debezium-connector.properties /opt/debezium-cassandra/conf/
