spring.application.name=mongo
spring.jmx.enabled=false

spring.data.mongodb.uri=mongodb+srv://admin:pass123@zeclusteour.nd7ugvt.mongodb.net/?retryWrites=true&w=majority&appName=ZeClusteour
spring.data.mongodb.database=darbsciu_rankuciu_klubas

redis.host=localhost
redis.port=8090
redis.timeout=2000

redis.pool.max-total=50
redis.pool.max-idle=10
redis.pool.min-idle=5

cassandra.contact-points=127.0.0.1
cassandra.port=9042
cassandra.keyspace=darbsciu_rankuciu_klubas
cassandra.datacenter=datacenter1

neo4j.uri=bolt://localhost:7687
neo4j.username=neo4j
neo4j.password=darbsciu_rankuciu_klubas