include:
    # database setup
    # - ./containers/redis.yaml
    # - ./containers/neo4j.yaml
    - ./containers/cassandra.yaml
    
    # log replication setup
    # - ./containers/zookeeper.yaml
    # - ./containers/kafka.yaml
    # - ./containers/elasticsearch.yaml
    # - ./containers/kibana.yaml