connector.name=test_connector
commit.log.relocation.dir=/var/lib/cassandra/cdc_raw
commit.log.real.time.processing.enabled=true
http.port=8000

# cassandra configuration
cassandra.config=/opt/cassandra/conf/cassandra.yaml
cassandra.driver.config.file=/debezium/application.conf
cassandra.hosts=127.0.0.1
cassandra.port=9042
cassandra.contact.points=cassandra

snapshot.consistency=ONE
snapshot.mode=ALWAYS

offset.backing.store.dir=/debezium/offsets

# kafka configuration
kafka.producer.bootstrap.servers=kafka:9092
kafka.producer.retries=3
kafka.producer.retry.backoff.ms=1000
topic.prefix=test_prefix

key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter