FROM confluentinc/cp-kafka-connect:7.6.0

USER root
RUN microdnf update && microdnf install -y unzip

# Clean start
RUN rm -rf /usr/share/confluent-hub-components/*
WORKDIR /usr/share/confluent-hub-components/

# 1. Install Elasticsearch Sink (Directly to its own folder)
RUN curl -L -o es-sink.zip https://api.hub.confluent.io/api/plugins/confluentinc/kafka-connect-elasticsearch/versions/14.1.1/archive \
    && unzip es-sink.zip \
    && rm es-sink.zip

# 2. Install Debezium MySQL (Directly to its own folder)
# This provides the Unwrap SMT and all its dependencies in a clean way
RUN curl -L -o debezium.tar.gz https://repo1.maven.org/maven2/io/debezium/debezium-connector-mysql/2.5.4.Final/debezium-connector-mysql-2.5.4.Final-plugin.tar.gz \
    && tar -xzf debezium.tar.gz \
    && rm debezium.tar.gz

RUN chown -R 1000:1000 /usr/share/confluent-hub-components/